config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions
  get 'home/index'
  root 'home#index'

  namespace:admin do
    root 'master#index'
    resources :ages
    resources :classes
    resources :fees
    resources :payments
    resources :sections
    resources :students
    get "/payment/:id", to:"payments#send_mail", as:'mail'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/age.rb
class Age < ApplicationRecord
  belongs_to :classe

  validates :date_from, presence: true
  validates :date_to, presence: true
  validates :age_from, presence: true
  validates :age_to, presence: true
  validates :date_as, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classe.rb
class Classe < ApplicationRecord
  has_many :students, dependent: :destroy
  has_many :sections, dependent: :destroy
  has_one :age, dependent: :destroy
  has_one :fee, dependent: :destroy

  validates :classe, presence: true
  validates :stage, presence: true
  validates :description, presence: true
end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :classe

  validates :admission_fee, presence: true
  validates :annual_fee, presence: true
  validates :caution_money, presence: true
  validates :tution_fee, presence: true
  validates :almanac_fee, presence: true
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :classe

  validates :section_name, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
  has_one_attached :image
  has_one_attached :file
  belongs_to :classe
  belongs_to :user

  MODE_LIST = ["Cash", "Cheque", "Draft", "Credit Card", "Debit Card", "Net Banking"]
  STATUS_LIST = ["Pending", "Processed", "Approved", "Failed"]

  validates :name, presence: true
  validates :birth_date, presence: true
  validates :academic_year, presence: true
  validates :father_name, presence: true
  validates :mother_name, presence: true
  validates :address, presence: true
  validates :contact, presence: true, length: { is: 10 }
  validates :email, presence: true
  validates :image, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg']
  validates :file, attached: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :students

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :name, presence: true, length: { maximum: 30, minimum: 2 }
  validates :email, presence: true, length: { maximum: 30, minimum: 2 }, uniqueness: { case_sensitive: false } , format: { with: VALID_EMAIL_REGEX }

end

app/controllers/admin/classes_controller.rb
class Admin::ClassesController < ApplicationController
  before_action :is_admin?
  def index
    @classs = Classe.all
  end

  def show
    @class = Classe.find(params[:id])
  end

  def new
    @class = Classe.new
    @section = Section.all
  end

  def edit
    @class = Classe.find(params[:id])
    @section = Section.all
  end

  def create
    @class = Classe.new(classe_params)
    if @class.save
      redirect_to [:admin, @class]
    else
      render 'new'
    end
  end

  def update
    @class = Classe.find(params[:id])
    if @class.update(classe_params)
      redirect_to [:admin, @class]
    else
      render 'edit'
    end
  end

  def destroy
    @class = Classe.find(params[:id])
    @class.destroy

    redirect_to admin_classes_path
  end

  private
    def classe_params
      params.require(:classe).permit(:classe, :stage, :description)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    user = User.new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:danger] = "Logged out!"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      if(session[:user_id] != nil)
        if current_user.admin == true
          @user.admin = true
          @user.save
          redirect_to root_url, notice: "Thank you for creating account!"
        end
      else
        if(session[:user_id])
          redirect_to root_url, notice: "Thank you for creating account!"
        else
          redirect_to new_session_url, notice: "Thank you for creating account!"
        end
      end
    else
      render "new"
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/ages_helper.rb
module AgesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/master_helper.rb
module MasterHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/classes/_form.html.erb
<%= form_with(model: [:admin, @class], local: true) do |form| %>

  <% if @class.errors.any? %>
    <div id="error_explanation">
      <div class="head">
        <h2>
          <%= pluralize(@class.errors.count, "error") %> Prohibited
          this location from being saved:
        </h2>
      </div>
      <div class="error-list">
        <ul>
          <% @class.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="input-form">
    <div class="input-field">
      <%= form.label :classe %><br>
      <div class="input-section">
        <%= form.text_field :classe, placeholder:"  Enter Class" %>
      </div>
    </div>

    <div class="input-field">
      <%= form.label :stage %><br>
      <div class="input-section">
        <%= form.text_field :stage, placeholder:"  Enter Stage Name" %>
      </div>
    </div>

    <div class="input-field">
      <%= form.label :description %><br>
      <div class="input-section">
        <%= form.text_area :description, placeholder:"  Enter Description" %>
      </div>
    </div>

    <div class="input-field">
      <%= form.label :classe_id %><br>
      <div class="input-section">
        <%= form.select :classe_id, Section.all.collect { |c| [c.section_name, c.id] } %>
      </div>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/admin/classes/edit.html.erb
<h2>Edit Class:</h2>

<%= render 'form' %>

<div class="nav-back">
  <%= link_to 'Back', admin_classes_path %>
</div>

app/views/admin/classes/index.html.erb
<h1>Listing Classes</h1>
<div class="add-button">
  <%= link_to "Add New Class", new_admin_class_path %>
</div>
<table>
  <tr>
    <th>Class</th>
    <th>Stage</th>
  </tr>

  <% @classs.each do |classe| %>
    <tr>
      <td><%= classe.classe %></td>
      <td><%= classe.stage %></td>
      <td class="feature"><%= link_to 'Show', admin_class_path(classe) %></td>
      <td class="feature"><%= link_to 'Edit', edit_admin_class_path(classe) %></td>
      <td class="feature"><%= link_to 'Destroy', admin_class_path(classe),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<div class="nav-back">
  <%= link_to 'Back', root_path %>
</div>

app/views/admin/classes/new.html.erb
<h1>New Class</h1>

<%= render 'form' %>

<div class="nav-back">
  <%= link_to 'Back', admin_classes_path %>
</div>

app/views/admin/classes/show.html.erb
<h2>Class Details:</h2>
<div class="show_class">
  <div class="info">
    <div class="heading">
      <strong>Class:</strong>
    </div>
    <div class="data">
      <%= @class.classe %>
    </div>
  </div>
  <div class="info">
    <div class="heading">
      <strong>Stage Name:</strong>
    </div>
    <div class="data">
      <%= @class.stage %>
    </div>
  </div>
  <div class="info">
    <div class="heading">
      <strong>Description:</strong>
    </div>
    <div class="data">
      <%= @class.description %>
    </div>
  </div>
</div>

<div class="nav-back">
  <%= link_to 'Back', admin_classes_path %>
</div>