config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions
  get 'home/index'
  root 'home#index'

  namespace:admin do
    root 'master#index'
    resources :ages
    resources :classes
    resources :fees
    resources :payments
    resources :sections
    resources :students
    get "/payment/:id", to:"payments#send_mail", as:'mail'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/age.rb
class Age < ApplicationRecord
  belongs_to :classe

  validates :date_from, presence: true
  validates :date_to, presence: true
  validates :age_from, presence: true
  validates :age_to, presence: true
  validates :date_as, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classe.rb
class Classe < ApplicationRecord
  has_many :students, dependent: :destroy
  has_many :sections, dependent: :destroy
  has_one :age, dependent: :destroy
  has_one :fee, dependent: :destroy

  validates :classe, presence: true
  validates :stage, presence: true
  validates :description, presence: true
end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :classe

  validates :admission_fee, presence: true
  validates :annual_fee, presence: true
  validates :caution_money, presence: true
  validates :tution_fee, presence: true
  validates :almanac_fee, presence: true
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :classe

  validates :section_name, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
  has_one_attached :image
  has_one_attached :file
  belongs_to :classe
  belongs_to :user

  MODE_LIST = ["Cash", "Cheque", "Draft", "Credit Card", "Debit Card", "Net Banking"]
  STATUS_LIST = ["Pending", "Processed", "Approved", "Failed"]

  validates :name, presence: true
  validates :birth_date, presence: true
  validates :academic_year, presence: true
  validates :father_name, presence: true
  validates :mother_name, presence: true
  validates :address, presence: true
  validates :contact, presence: true, length: { is: 10 }
  validates :email, presence: true
  validates :image, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg']
  validates :file, attached: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :students

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :name, presence: true, length: { maximum: 30, minimum: 2 }
  validates :email, presence: true, length: { maximum: 30, minimum: 2 }, uniqueness: { case_sensitive: false } , format: { with: VALID_EMAIL_REGEX }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      if(session[:user_id] != nil)
        if current_user.admin == true
          @user.admin = true
          @user.save
          redirect_to root_url, notice: "Thank you for creating account!"
        end
      else
        if(session[:user_id])
          redirect_to root_url, notice: "Thank you for creating account!"
        else
          redirect_to new_session_url, notice: "Thank you for creating account!"
        end
      end
    else
      render "new"
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/ages_helper.rb
module AgesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/master_helper.rb
module MasterHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolAdmission</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="message">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
    </div>
    <div class="navbar">
      <div class="user-name">
        <% if current_user %>
          Logged in as <%= current_user.name %>
      </div>
        <% if current_user.admin? %>
        <div class="navbar-content">
          <div class="link"><%= link_to "Sections", admin_sections_path %></div>
          <div class="link"><%= link_to "Class", admin_classes_path %></div>
          <div class="link"><%= link_to "Fees Structure", admin_fees_path %></div>
          <div class="link"><%= link_to "Age Criteria", admin_ages_path %></div>
          <div class="link"><%= link_to "Student", admin_students_path %></div>
          <div class="link"><%= link_to "Payment", admin_payments_path %></div>
        </div>
        <% end %>
        <div class="dropdown">
        <button class="dropbtn">Options
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
          <div class="nav-item"><%= link_to "Sign Out", session_path("current"), method: "delete" %></div>
          <% if current_user.admin? %>
            <div class="nav-item"><%= link_to "Create New Admin", new_user_path %></div>
          <% else %>
            <div class="nav-item"><%= link_to "Application Form", new_admin_student_path %></div>
            <div class="nav-item"><%= link_to "Dasboard", admin_students_path %></div>
          <% end %>
          <div class="nav-item"><%= link_to "Profile", user_path(current_user.id) %></div>
        </div>
        <% else %>
          <div class="nav-field"><%= link_to "Sign Up", new_user_path %></div>
          <div class="nav-field"><%= link_to "Sign In", new_session_path %></div>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>